* このサイトについて

忙しい毎日。

その隙をついて、様々な試練がTODOリストに襲いかかってきます。

- 簡単にできると思ってたけど、いろいろ難しくて途中で断念した
- 夜中のノリでこれをやろうと決めたけど、よくよく考えたら馬鹿げたアイデアだった
- 友人からプロジェクトを持ちかけられて準備してたら、「アレ無しの方向で」と言われた
- 自己啓発的な本を読んで、瞑想を朝のルーチンに決めたけど、いつもの三日坊主

ときに彼らは我々の思考と時間を奪い、勝手に義務感を押しつけ、あげくの果てに挫折感を植えつけることすらあります。

しかし達成できなかったとはいえ、一度は旅の途中で出会った彼ら。

行ごと消して「なかったこと」にするのではなく、「ご縁がなかったTODOアイテム」として手厚く葬ってやりたい。

ここはそんな彼らのための墓場です。

* ご注意

- 墓場なので、めでたく達成できたTODOアイテムはここには運ばれません
- 仕事上のTODOはクローズドなところに保管されるので、そういうのもここには来ません
- あと、ポストイットに書いたやつとかも

* しくみとか

このサイトは墓守がふだん使っているTODOリストから自動生成されています。

TODOリストは[[https://ja.wikipedia.org/wiki/GNU_Emacs][Emacs]]の[[https://orgmode.org/ja/][org-mode]]で管理されており、不要になったTODOアイテムの上で ~M-0~ を押すとこのサイトに転送されるという塩梅です。

サイト自体は[[https://www.netlify.com/][Netlify]]と[[https://gohugo.io/][Hugo]]に任せきりですが、具体的には下記のような流れになっています。

1. org-modeからTODOアイテムの1行からorgファイルを生成
2. org-modeから ~git add~, ~commit~, ~push~ を実行
3. Netlifyがリポジトリの更新を検知
4. Hugoがorgファイルを取り込んでサイトをビルド

* 運用してみた感想とか

このサイトを作ることで、不要なTODOアイテムを削除するというネガティブな行為が少し明るくなった気がします。

また、失敗したプロジェクトでもあとで見返すと、その時は分からなかった解決方法が見つかることもあります。

それに、黒歴史も大きな塊のまま忘れようとするのではなく、こういうふうに細切れにして残すと内容を把握しやすく、精神的なダメージも少ないことに気づきました（なんか ~git diff~ で見返したときと似てる）。

Hugoがorgファイルを直接扱えるのがいい感じ。

* リンクとか
- [[https://github.com/hidsh/cemetery][このサイトのGitHubリポジトリ]]
- [[https://github.com/hidsh/.emacs.d][今の.emacs.d]]
- [[https://twitter.com/_gnrr][Twitter]]
- [[https://zzz-kbd.com/][zzz-kbd]]
